# Copyright Bruno Dutra 2015-2016
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp
os: linux
sudo: false

git:
  depth: 1

env:
    global:
      - secure: "DuBGzmeKiWMm5m0+uZhutjzCffB2PbixmuMm3IZWUi7/uAam4PPI37oeqVTIytxxfpgRvfR2ah75eJyU6ab72MBoHxGkHem10RAvhC/vPYbLZu545qfSGatyTI9R6NfERUxi7YIxjs6D8c4D/5k3gMoCbMUkU1Lze1708lknh5U="

    matrix:
      - BOGUS_JOB=true

addons:
    apt:
        packages: &cmake
          - cmake
          - cmake-data
        sources: &sources
          - george-edison55-precise-backports
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise
          - llvm-toolchain-precise-3.5
          - llvm-toolchain-precise-3.6
          - llvm-toolchain-precise-3.7
          - llvm-toolchain-precise-3.8

matrix:
    exclude:
      - env: BOGUS_JOB=true

    include:
      - compiler: clang++
        env: BUILD_DOC=true

      - compiler: clang++
        env: CXX_VERSION=3.5
        addons:
            apt:
                packages:
                  - *cmake
                  - clang-3.5
                  - libstdc++-5-dev
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.6
        addons:
            apt:
                packages:
                  - *cmake
                  - clang-3.6
                  - libstdc++-5-dev
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.7
        addons:
            apt:
                packages:
                  - *cmake
                  - clang-3.7
                  - libstdc++-5-dev
                sources: *sources

      - compiler: clang++
        env: CXX_VERSION=3.8
        addons:
            apt:
                packages:
                  - *cmake
                  - clang-3.8
                  - libstdc++-5-dev
                sources: *sources

      - compiler: g++
        env: CXX_VERSION=4.9
        addons:
            apt:
                packages:
                  - *cmake
                  - g++-4.9
                sources: *sources

      - compiler: g++
        env: CXX_VERSION=5
        addons:
            apt:
                packages:
                  - *cmake
                  - g++-5
                sources: *sources

before_install:
  - git config --global user.name "Travis Bot"
  - git config --global user.email "\<\>"

  - METAL_SOURCE_PATH="${TRAVIS_BUILD_DIR}"
  - EXTERNAL_SOURCE_PATH="${METAL_SOURCE_PATH}/example/external/"

  - METAL_BUILD_PATH="${TRAVIS_BUILD_DIR}/build"
  - mkdir -p "${METAL_BUILD_PATH}"

  - METAL_INSTALL_PATH="${TRAVIS_BUILD_DIR}/install"
  - mkdir -p "${METAL_INSTALL_PATH}"

  - EXTERNAL_BUILD_PATH="${METAL_BUILD_PATH}/example/external/"
  - mkdir -p "${EXTERNAL_BUILD_PATH}"

  - DEPS_PATH="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_PATH}"

  - |
    if [[ -n "${TRAVIS_TAG}" ]]
    then
        METAL_VERSION="${TRAVIS_TAG}"
    else
        METAL_VERSION=$( \
            curl -Ls https://api.github.com/repos/brunocodutra/metal/releases/latest | \
            awk -F'"' '/tag_name/{print $4}' \
        )
    fi

  - METAL_VERSION="${METAL_VERSION%%-*}"
  - METAL_VERSION="${METAL_VERSION##*v}"
  - echo "METAL_VERSION=${METAL_VERSION}"

install:
  - |
    if [[ "${BUILD_DOC}" == "true" ]]
    then
        # download the latest doxygen available
        DOXYGEN_FTP="ftp://ftp.stack.nl/pub/users/dimitri/"
        DOXYGEN_PKG=$(travis_retry curl -Ls "${DOXYGEN_FTP}" | grep -Eo "doxygen-[0-9.]+linux[.]bin[.]tar[.]gz" | sort -V | tail -1)
        DOXYGEN_URL="${DOXYGEN_FTP}/${DOXYGEN_PKG}"
        echo "DOXYGEN_URL=${DOXYGEN_URL}" &&
        mkdir -p "${DEPS_PATH}/doxygen" &&
        travis_retry curl -L "${DOXYGEN_URL}" | tar --strip-components=1 -xz -C "${DEPS_PATH}/doxygen" &&
        export PATH=${DEPS_PATH}/doxygen/bin:${PATH} &&
        doxygen --version
    fi

before_script:
  - CMAKE_ARGS=("-DCMAKE_INSTALL_PREFIX=${METAL_INSTALL_PATH}")
  - |
    if [[ -n "${CXX}" && -n "${CXX_VERSION}" ]]
    then
        CMAKE_ARGS+=("-DCMAKE_CXX_COMPILER=${CXX}-${CXX_VERSION}")
    fi

  - (cd "${METAL_BUILD_PATH}" && cmake "${METAL_SOURCE_PATH}" ${CMAKE_ARGS[@]} && make install)

  - CMAKE_ARGS+=("-DCMAKE_PREFIX_PATH=${METAL_INSTALL_PATH}")
  - |
    if [[ -n "${METAL_VERSION}" ]]
    then
        CMAKE_ARGS+=("-DMETAL_VERSION=${METAL_VERSION}")
    fi

  - (cd "${EXTERNAL_BUILD_PATH}" && cmake "${EXTERNAL_SOURCE_PATH}" ${CMAKE_ARGS[@]})

script:
  - |
    if [[ "${BUILD_DOC}" == "true" ]]
    then
        (cd "${METAL_BUILD_PATH}" && make doc) &&
        if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]
        then
            git clone https://brunocodutra:${GITHUB_TOKEN}@github.com/brunocodutra/metal -q --depth 1 --branch=gh-pages "${METAL_BUILD_PATH}/doc/gh-pages" &> /dev/null &&
            cp -r "${METAL_BUILD_PATH}/doc/gh-pages/.git/" "${METAL_BUILD_PATH}/doc/html/" &> /dev/null &&
            git -C "${METAL_BUILD_PATH}/doc/html/" add --all . &> /dev/null &&
            git -C "${METAL_BUILD_PATH}/doc/html/" commit --allow-empty -m "updating to $(git -C ${METAL_SOURCE_PATH} rev-parse --short HEAD)" &> /dev/null &&
            git -C "${METAL_BUILD_PATH}/doc/html/" push origin gh-pages &> /dev/null
        fi
    else
        (cd "${EXTERNAL_BUILD_PATH}" && make all) &&
        (cd "${METAL_BUILD_PATH}" && ctest --output-on-failure)
    fi
