environment:
    matrix:
      - DEPLOY: true
      - CHECK_DOC: true

      - COMPILER: Visual Studio 14 2015
        GENERATOR: "Visual Studio 14 2015"
        CXXFLAGS: /DMETAL_TEST_GEN_LIMIT=7
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

      - COMPILER: Visual Studio 15 2017
        GENERATOR: "Visual Studio 15 2017"
        CXXFLAGS: /DMETAL_TEST_GEN_LIMIT=7
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

      - COMPILER: MinGW 5
        GENERATOR: "MinGW Makefiles"
        BINDIR: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

      - COMPILER: MinGW 6
        GENERATOR: "MinGW Makefiles"
        BINDIR: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration:
  - Debug

install:
  - git -C "%APPVEYOR_BUILD_FOLDER%" submodule update --init --recursive

  - if "%CHECK_DOC%" equ "true" (choco install doxygen.install)

before_build:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if defined BINDIR (set "PATH=%BINDIR%;%PATH%")

  - set "SOURCE_PATH=%APPVEYOR_BUILD_FOLDER%"

  - set "BUILD_PATH=%APPVEYOR_BUILD_FOLDER%\build"
  - mkdir "%BUILD_PATH%"

  - set "INSTALL_PATH=%APPVEYOR_BUILD_FOLDER%\install"
  - mkdir "%INSTALL_PATH%"

  - set "CMAKE_ARGS=%SOURCE_PATH% -DCMAKE_INSTALL_PREFIX="%INSTALL_PATH%""
  - if defined GENERATOR (set "CMAKE_ARGS=%CMAKE_ARGS% -G"%GENERATOR%"")
  - set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBOOST_ROOT=C:/Libraries/boost/"

  - cmake --version
  - echo cmake %CMAKE_ARGS%
  - pushd "%BUILD_PATH%" && cmake %CMAKE_ARGS% & popd

build_script:
  - if "%DEPLOY%" equ "true" (
        cmake --build "%BUILD_PATH%" --target install --config "%CONFIGURATION%"
    ) else if "%CHECK_DOC%" equ "true" (
        cmake --build "%BUILD_PATH%" --target doc --config "%CONFIGURATION%"
    ) else (
        pushd "%BUILD_PATH%" && ctest -C "%CONFIGURATION%" --output-on-failure -E "^test.(format|header)" & popd
    )

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/5daddf3d6cedeb27ba90
    on_build_failure: true
    on_build_status_changed: true
